export const Command = {
  INIT_FRAME: 'init-frame',
  SET_PLUGINS_CONFIGURATION: 'set-plugins-configuration',
  CONNECTION_PING: 'connection-ping',
  CONNECTION_PONG: 'connection-pong',

  CONSOLE_LOG: 'console-log',
  EVAL_COMMAND: 'eval-command',
  EVAL_COMMAND_RESPONSE: 'eval-command/response',

  READ_LOCATION: 'read-location',
  READ_LOCATION_RESPONSE: 'read-location/response',
  LOCATION_SET: 'location-set',
  LOCATION_SET_HASH: 'location-set-hash',
  LOCATION_RELOAD: 'location-reload',
  HISTORY_BACK: 'history-back',
  HISTORY_FORWARD: 'history-forward',

  READ_COOKIES: 'read-cookies',
  READ_COOKIES_RESPONSE: 'read-cookies/response',
  COOKIE_SET: 'cookie-set',
  COOKIE_REMOVE: 'cookie-remove',
  COOKIES_CLIPBOARD_EXPORT: 'cookies-clipboard-export',
  COOKIES_BULK_SET: 'cookies-bulk-set',

  READ_LOCAL_STORAGE: 'read-local-storage',
  READ_LOCAL_STORAGE_RESPONSE: 'read-local-storage/response',
  LOCAL_STORAGE_SET: 'local-storage-set',
  LOCAL_STORAGE_REMOVE: 'local-storage-remove',
  LOCAL_STORAGE_CLIPBOARD_EXPORT: 'local-storage-clipboard-export',
  LOCAL_STORAGE_BULK_SET: 'local-storage-bulk-set',

  READ_SESSION_STORAGE: 'read-session-storage',
  READ_SESSION_STORAGE_RESPONSE: 'read-session-storage/response',
  SESSION_STORAGE_SET: 'session-storage-set',
  SESSION_STORAGE_REMOVE: 'session-storage-remove',
  SESSION_STORAGE_CLIPBOARD_EXPORT: 'session-storage-clipboard-export',
  SESSION_STORAGE_BULK_SET: 'session-storage-bulk-set',

  DOM_NODE_LOOKUP: 'dom-node-lookup',
  DOM_NODE_LOOKUP_RESPONSE: 'dom-node-lookup/response',
  DOM_QUERY_SELECTOR: 'dom-query-selector',
  DOM_QUERY_SELECTOR_RESPONSE: 'dom-query-selector/response',
  DOM_NODE_COMPUTED_STYLE: 'dom-node-computed-style',
  DOM_NODE_COMPUTED_STYLE_RESPONSE: 'dom-node-computed-style/response',
  DOM_NODE_SET_ATTRIBUTE: 'dom-node-set-attribute',
  DOM_NODE_SET_STYLE: 'dom-node-set-style',
  DOM_NODE_COPY_QUERY: 'dom-node-copy-query',
  DOM_NODE_COPY_HTML: 'dom-node-copy-html',
  DOM_NODE_COPY_TEXT: 'dom-node-copy-text',
  DOM_NODE_ASSIGN_VARIABLE: 'dom-node-assign-variable',

  PP_ZOOM_SET: 'pixel-perfect-zoom-set',
  PP_RULER_SHOW: 'pixel-perfect-ruler-show',
  PP_RULER_HIDE: 'pixel-perfect-ruler-hide',
  PP_GRID_SHOW: 'pixel-perfect-grid-show',
  PP_GRID_HIDE: 'pixel-perfect-grid-hide',
  PP_COLUMNS_SHOW: 'pixel-perfect-columns-show',
  PP_COLUMNS_HIDE: 'pixel-perfect-columns-hide',
  PP_IMAGE_SHOW: 'pixel-perfect-image-show',
  PP_IMAGE_HIDE: 'pixel-perfect-image-hide',
  PP_IMAGE_SETTINGS: 'pixel-perfect-image-settings',
  PP_WINDOW_SIZE: 'pixel-perfect-window-size',
  PP_WINDOW_SET_SIZE: 'pixel-perfect-window-set-size',
  PP_MOUSE_POSITION: 'pixel-perfect-mouse-position',

  XHR_UPDATE: 'network-update',

  WEBSOCKET_CREATED: 'websocket-created',
  WEBSOCKET_UPDATED: 'websocket-updated',
  WEBSOCKET_MESSAGE: 'websocket-message',
  WEBSOCKET_MESSAGE_SEND: 'websocket-message-send',

  REDUX_ACTION: 'redux-action',

  TEXTDATA_SHOW: 'textdata-show',

  INJECTION_EXECUTE: 'injection-execute',
};
